// Code generated by protoc-gen-go. DO NOT EDIT.
// source: car.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CarReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarReq) Reset()         { *m = CarReq{} }
func (m *CarReq) String() string { return proto.CompactTextString(m) }
func (*CarReq) ProtoMessage()    {}
func (*CarReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{0}
}

func (m *CarReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarReq.Unmarshal(m, b)
}
func (m *CarReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarReq.Marshal(b, m, deterministic)
}
func (m *CarReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarReq.Merge(m, src)
}
func (m *CarReq) XXX_Size() int {
	return xxx_messageInfo_CarReq.Size(m)
}
func (m *CarReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CarReq.DiscardUnknown(m)
}

var xxx_messageInfo_CarReq proto.InternalMessageInfo

func (m *CarReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CarResp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint64   `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarResp) Reset()         { *m = CarResp{} }
func (m *CarResp) String() string { return proto.CompactTextString(m) }
func (*CarResp) ProtoMessage()    {}
func (*CarResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{1}
}

func (m *CarResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarResp.Unmarshal(m, b)
}
func (m *CarResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarResp.Marshal(b, m, deterministic)
}
func (m *CarResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarResp.Merge(m, src)
}
func (m *CarResp) XXX_Size() int {
	return xxx_messageInfo_CarResp.Size(m)
}
func (m *CarResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CarResp.DiscardUnknown(m)
}

var xxx_messageInfo_CarResp proto.InternalMessageInfo

func (m *CarResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CarResp) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CarListResp struct {
	List                 []*CarResp `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CarListResp) Reset()         { *m = CarListResp{} }
func (m *CarListResp) String() string { return proto.CompactTextString(m) }
func (*CarListResp) ProtoMessage()    {}
func (*CarListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{2}
}

func (m *CarListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarListResp.Unmarshal(m, b)
}
func (m *CarListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarListResp.Marshal(b, m, deterministic)
}
func (m *CarListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarListResp.Merge(m, src)
}
func (m *CarListResp) XXX_Size() int {
	return xxx_messageInfo_CarListResp.Size(m)
}
func (m *CarListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CarListResp.DiscardUnknown(m)
}

var xxx_messageInfo_CarListResp proto.InternalMessageInfo

func (m *CarListResp) GetList() []*CarResp {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*CarReq)(nil), "proto.CarReq")
	proto.RegisterType((*CarResp)(nil), "proto.CarResp")
	proto.RegisterType((*CarListResp)(nil), "proto.CarListResp")
}

func init() { proto.RegisterFile("car.proto", fileDescriptor_f8b9800c53a1ba42) }

var fileDescriptor_f8b9800c53a1ba42 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4e, 0x2c, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x32, 0x5c, 0x6c, 0xce, 0x89, 0x45,
	0x41, 0xa9, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x92, 0x31, 0x17, 0x3b, 0x58, 0xb6, 0xb8, 0x00, 0x9b, 0xb4, 0x90, 0x08,
	0x17, 0x6b, 0x41, 0x51, 0x66, 0x72, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x84, 0xa3,
	0x64, 0xc8, 0xc5, 0xed, 0x9c, 0x58, 0xe4, 0x93, 0x59, 0x5c, 0x02, 0xd6, 0xa8, 0xc4, 0xc5, 0x92,
	0x93, 0x59, 0x5c, 0x22, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0x07, 0xb1, 0x5e, 0x0f, 0x6a,
	0x6c, 0x10, 0x58, 0xce, 0xa8, 0x83, 0x91, 0x8b, 0xcb, 0x39, 0xb1, 0x28, 0x38, 0xb5, 0xa8, 0x2c,
	0x33, 0x39, 0x55, 0x48, 0x93, 0x8b, 0x05, 0xa4, 0x5d, 0x88, 0x17, 0x59, 0x71, 0xa1, 0x94, 0x10,
	0x82, 0x0b, 0x37, 0x5d, 0x8d, 0x8b, 0x35, 0xb0, 0x34, 0xb5, 0xa8, 0x12, 0x5d, 0x2d, 0x9a, 0x3d,
	0x42, 0xea, 0x5c, 0x6c, 0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0x04, 0x14, 0x26, 0xb1, 0x81, 0xb9,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x73, 0xec, 0xcc, 0x2b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CarServiceClient is the client API for CarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarServiceClient interface {
	List(ctx context.Context, in *CarReq, opts ...grpc.CallOption) (*CarListResp, error)
	Query(ctx context.Context, in *CarReq, opts ...grpc.CallOption) (*CarResp, error)
	Update(ctx context.Context, in *CarReq, opts ...grpc.CallOption) (*CarResp, error)
}

type carServiceClient struct {
	cc *grpc.ClientConn
}

func NewCarServiceClient(cc *grpc.ClientConn) CarServiceClient {
	return &carServiceClient{cc}
}

func (c *carServiceClient) List(ctx context.Context, in *CarReq, opts ...grpc.CallOption) (*CarListResp, error) {
	out := new(CarListResp)
	err := c.cc.Invoke(ctx, "/proto.CarService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceClient) Query(ctx context.Context, in *CarReq, opts ...grpc.CallOption) (*CarResp, error) {
	out := new(CarResp)
	err := c.cc.Invoke(ctx, "/proto.CarService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceClient) Update(ctx context.Context, in *CarReq, opts ...grpc.CallOption) (*CarResp, error) {
	out := new(CarResp)
	err := c.cc.Invoke(ctx, "/proto.CarService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarServiceServer is the server API for CarService service.
type CarServiceServer interface {
	List(context.Context, *CarReq) (*CarListResp, error)
	Query(context.Context, *CarReq) (*CarResp, error)
	Update(context.Context, *CarReq) (*CarResp, error)
}

// UnimplementedCarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCarServiceServer struct {
}

func (*UnimplementedCarServiceServer) List(ctx context.Context, req *CarReq) (*CarListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedCarServiceServer) Query(ctx context.Context, req *CarReq) (*CarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedCarServiceServer) Update(ctx context.Context, req *CarReq) (*CarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterCarServiceServer(s *grpc.Server, srv CarServiceServer) {
	s.RegisterService(&_CarService_serviceDesc, srv)
}

func _CarService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CarService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).List(ctx, req.(*CarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CarService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).Query(ctx, req.(*CarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CarService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).Update(ctx, req.(*CarReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CarService",
	HandlerType: (*CarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CarService_List_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _CarService_Query_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CarService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car.proto",
}
