// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/gogf/gf/frame/g"
	"log"
	"my-goframe/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// Fill with you ideas below.
// 不推荐写在这里
func QueryUser() []User {
	model := g.DB().Model("user")
	//model := dao.User
	resp, err := model.Where("name = ?", "a").All()
	if err != nil {
		log.Println("user query error:", err)
		return nil
	}
	//log.Printf("%+v\n", resp)

	var users []User
	for _, v := range resp {
		users = append(users, User{
			Id:       v["id"].Uint(),
			Name:     v["name"].String(),
			Age:      v["age"].Uint(),
			Birthday: v["birthday"].GTime(),
		})
	}
	return users
}
