// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package mail_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求消息
type MailRequest struct {
	Mail                 string   `protobuf:"bytes,1,opt,name=Mail,proto3" json:"Mail,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailRequest) Reset()         { *m = MailRequest{} }
func (m *MailRequest) String() string { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()    {}
func (*MailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *MailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailRequest.Unmarshal(m, b)
}
func (m *MailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailRequest.Marshal(b, m, deterministic)
}
func (m *MailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailRequest.Merge(m, src)
}
func (m *MailRequest) XXX_Size() int {
	return xxx_messageInfo_MailRequest.Size(m)
}
func (m *MailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailRequest proto.InternalMessageInfo

func (m *MailRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *MailRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 响应消息
type MailResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailResponse) Reset()         { *m = MailResponse{} }
func (m *MailResponse) String() string { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()    {}
func (*MailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *MailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailResponse.Unmarshal(m, b)
}
func (m *MailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailResponse.Marshal(b, m, deterministic)
}
func (m *MailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailResponse.Merge(m, src)
}
func (m *MailResponse) XXX_Size() int {
	return xxx_messageInfo_MailResponse.Size(m)
}
func (m *MailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailResponse proto.InternalMessageInfo

func (m *MailResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*MailRequest)(nil), "mail_proto.MailRequest")
	proto.RegisterType((*MailResponse)(nil), "mail_proto.MailResponse")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x02, 0xb3, 0xe3, 0xc1, 0x6c, 0x25, 0x53, 0x2e, 0x6e,
	0xdf, 0xc4, 0xcc, 0x9c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x16, 0x10,
	0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x06, 0x89, 0x85, 0xa4, 0x56, 0x94, 0x48,
	0x30, 0x41, 0xc4, 0x40, 0x6c, 0x25, 0x39, 0x2e, 0x1e, 0x88, 0xb6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x3e, 0x2e, 0x26, 0xff, 0x6c, 0xb0, 0x2e, 0x8e, 0x20, 0x26, 0xff, 0x6c, 0x23, 0x3f,
	0x88, 0xb1, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xf6, 0x5c, 0x1c, 0xc1, 0xa9, 0x79,
	0x29, 0x60, 0xe3, 0xc4, 0xf5, 0x10, 0xd6, 0xeb, 0x21, 0xd9, 0x2d, 0x25, 0x81, 0x29, 0x01, 0x31,
	0x5d, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x08, 0x64, 0xf3,
	0x3e, 0xc7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailServiceClient interface {
	SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error)
}

type mailServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailServiceClient(cc *grpc.ClientConn) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	out := new(MailResponse)
	err := c.cc.Invoke(ctx, "/mail_proto.MailService/SendMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
type MailServiceServer interface {
	SendMail(context.Context, *MailRequest) (*MailResponse, error)
}

// UnimplementedMailServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (*UnimplementedMailServiceServer) SendMail(ctx context.Context, req *MailRequest) (*MailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMail not implemented")
}

func RegisterMailServiceServer(s *grpc.Server, srv MailServiceServer) {
	s.RegisterService(&_MailService_serviceDesc, srv)
}

func _MailService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail_proto.MailService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendMail(ctx, req.(*MailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mail_proto.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _MailService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
