// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Product is the golang structure for table product.
type Product struct {
	Id    uint `orm:"id,primary" json:"id"`    // 自增id
	Price uint `orm:"price"      json:"price"` // 价格
}
