// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         uint        `orm:"id,primary"  json:"id"`         //
	Name       string      `orm:"name"        json:"name"`       //
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` //
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` //
	Age        uint        `orm:"age"         json:"age"`        //
	Birthday   *gtime.Time `orm:"birthday"    json:"birthday"`   //
}
